[workspace]
members = [
  "apps/shitview-slint",
  "crates/shitview-core",
  "crates/shitview-index",
  "crates/shitview-indexer",
  "crates/shitview-storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
crossbeam-channel = "0.5"
ignore = "0.4"
notify = "8"
rusqlite = { version = "0.37", features = ["bundled"] }
slint = "1"
slint-build = "1"
windows-sys = { version = "0.60", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }
